Traceback (most recent call last):
  File "C:\Users\alujan\miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\alujan\miniconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\alujan\miniconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\alujan\miniconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\alujan\miniconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\alujan\miniconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\alujan\miniconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\alujan\miniconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import statsmodels.api as sm
from linearmodels.panel.model import PanelOLS
from HARK.distribution import calc_expectation
from HARK.ConsumptionSaving.ConsIndShockModel import (
    IndShockConsumerType,
    init_lifecycle,
)

from HARK.Calibration.Income.IncomeTools import (
    parse_income_spec,
    parse_time_params,
    CGM_income,
)

from HARK.datasets.life_tables.us_ssa.SSATools import parse_ssa_life_table
from HARK.datasets.SCF.WealthIncomeDist.SCFDistTools import income_wealth_dists_from_scf
import matplotlib.pyplot as plt
import pandas as pd
from copy import copy
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mas[39;00m [38;5;21;01msm[39;00m
[1;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mlinearmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpanel[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodel[39;00m [38;5;28;01mimport[39;00m PanelOLS
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mHARK[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdistribution[39;00m [38;5;28;01mimport[39;00m calc_expectation
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mHARK[39;00m[38;5;21;01m.[39;00m[38;5;21;01mConsumptionSaving[39;00m[38;5;21;01m.[39;00m[38;5;21;01mConsIndShockModel[39;00m [38;5;28;01mimport[39;00m (
[0;32m      5[0m     IndShockConsumerType,
[0;32m      6[0m     init_lifecycle,
[0;32m      7[0m )

[1;31mModuleNotFoundError[0m: No module named 'linearmodels'
ModuleNotFoundError: No module named 'linearmodels'

